// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTzxOYGdAtg4dm4g4nlxjurlQgpntCSg',
    appId: '1:436937306861:web:a2b31ca2c099c9065752e4',
    messagingSenderId: '436937306861',
    projectId: 'medicoai-65160',
    authDomain: 'medicoai-65160.firebaseapp.com',
    storageBucket: 'medicoai-65160.firebasestorage.app',
    measurementId: 'G-STCDF6C7EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC20RMhT7HUQ9JUheWLouWNKOVEpk_gbg',
    appId: '1:436937306861:android:cf85ca7fe1d649e85752e4',
    messagingSenderId: '436937306861',
    projectId: 'medicoai-65160',
    storageBucket: 'medicoai-65160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iJVPeDceMSDYeZKk07P-Yb9MXxEGXlw',
    appId: '1:436937306861:ios:2c799a1e82ed8c5d5752e4',
    messagingSenderId: '436937306861',
    projectId: 'medicoai-65160',
    storageBucket: 'medicoai-65160.firebasestorage.app',
    iosBundleId: 'com.example.medicoai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iJVPeDceMSDYeZKk07P-Yb9MXxEGXlw',
    appId: '1:436937306861:ios:288a256b6a7d3a285752e4',
    messagingSenderId: '436937306861',
    projectId: 'medicoai-65160',
    storageBucket: 'medicoai-65160.firebasestorage.app',
    iosBundleId: 'it.aqila.farahmand.medicoai.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTzxOYGdAtg4dm4g4nlxjurlQgpntCSg',
    appId: '1:436937306861:web:745e12373506ba865752e4',
    messagingSenderId: '436937306861',
    projectId: 'medicoai-65160',
    authDomain: 'medicoai-65160.firebaseapp.com',
    storageBucket: 'medicoai-65160.firebasestorage.app',
    measurementId: 'G-1ECZKFGSK2',
  );
}
